baseURL = 'https://yunwuhai.github.io/'
languageCode = 'zh-cn'
title = '云雾海的博客'
theme = ["PaperMod"]

buildDrafts = false
buildExpired = false
buildFuture = false
enableRobotsTXT = true

[pagination]
  pagerSize = 5
pygmentsUseClasses = true

[markup.highlight]
noClasses = false

[[menu.main]]
identifier = "posts"
name = "目录"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 40

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 50

[minify]
disableXML = true
minifyOutput = true

[params]
DateFormat = "January 2, 2006"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowRssButtonInSectionTermList = false
ShowShareButtons = false
ShowWordCount = true
UseHugoToc = true
author = "云雾海"
comments = false
defaultTheme = "auto"
description = "云雾海的博客"
disableScrollToTop = false
disableSpecial1stPost = false
disableThemeToggle = false
env = "production"
hideSummary = false
hidemeta = false
images = ["<link or path of image for opengraph, twitter-cards>"]
keywords = ["Blog", "C/C++", "嵌入式", "Arduino", "USB", "桌面端", "C#", ".NET", "WPF", "Avalonia", "个人博客", "GitHub", "开源"]
showtoc = true
title = "Yunwuhai's Blog"
tocopen = false

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
Text = "Suggest Changes"
URL = "https://github.com/yunwuhai/yunwuhai.github.io/tree/master/content/posts"
appendFilePath = true

[params.fuseOpts]
distance = 1000
isCaseSensitive = false
keys = ["title", "permalink", "summary", "content"]
limit = 10
location = 0
minMatchCharLength = 0
shouldSort = true
threshold = 0.4

[params.homeInfoParams]
Content = "此处记录着我来时的路"
Title = "云筑"

[params.label]
icon = "/apple-touch-icon.png"
iconHeight = 35
text = "主页"

[params.profileMode]
enabled = true
imageHeight = 120
imageTitle = "我的头像"
imageUrl = "https://raw.githubusercontent.com/yunwuhai/blog-img/master/img/q4SymNypcxz7Dga.thumb.1000_0.png"
imageWidth = 120
title = "云筑"
subtitle = "此处记录着我来时的路"

[[params.profileMode.buttons]]
name = "目录"
url = "posts"

[[params.profileMode.buttons]]
name = "分类"
url = "categories"

[[params.profileMode.buttons]]
name = "标签"
url = "tags"

[[params.profileMode.buttons]]
name = "搜索"
url = "search"

[[params.profileMode.buttons]]
name = "归档"
url = "archives"

[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/16545463"

[[params.socialIcons]]
name = "github"
url = "https://github.com/yunwuhai"

[outputs]
home = ["HTML", "RSS", "JSON"]