baseURL = 'https://yunwuhai.github.io/'
languageCode = 'zh-cn'
title = '云雾海的博客'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'